/**
 * Search-result ranking engine.
 *
 * Assigns a composite score to each track based on multiple signals
 * (title match, duration quality, channel authority, popularity)
 * and returns the results sorted by descending score.
 */

import type { Track } from '@/types';

// ── Scoring weights ─────────────────────────────────────────────────────────

const TITLE_WEIGHT = 40;
const DURATION_WEIGHT = 25;
const CHANNEL_WEIGHT = 20;
const POPULARITY_WEIGHT = 15;

// ── Helpers ─────────────────────────────────────────────────────────────────

/**
 * Strip special characters, lowercase, and trim a string.
 */
function normalize(input: string): string {
  return input
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\s]/g, '')
    .replace(/\s+/g, ' ');
}

/**
 * Compute the title-match score (0 – TITLE_WEIGHT).
 *
 * Hierarchy: exact match > starts-with > contains > partial word overlap.
 */
function titleScore(normalizedTitle: string, normalizedQuery: string): number {
  if (!normalizedQuery) return 0;

  // Exact match
  if (normalizedTitle === normalizedQuery) return TITLE_WEIGHT;

  // Starts with the query
  if (normalizedTitle.startsWith(normalizedQuery)) {
    // Longer query relative to title → higher score
    const ratio = normalizedQuery.length / normalizedTitle.length;
    return TITLE_WEIGHT * (0.85 + 0.15 * ratio);
  }

  // Contains the query as a substring
  if (normalizedTitle.includes(normalizedQuery)) {
    const ratio = normalizedQuery.length / normalizedTitle.length;
    return TITLE_WEIGHT * (0.6 + 0.25 * ratio);
  }

  // Partial word overlap — check if every query word appears in the title
  const queryWords = normalizedQuery.split(' ');
  const titleWords = normalizedTitle.split(' ');
  const matches = queryWords.filter((qw) => titleWords.some((tw) => tw.includes(qw)));

  if (matches.length > 0) {
    const coverage = matches.length / queryWords.length;
    return TITLE_WEIGHT * 0.4 * coverage;
  }

  return 0;
}

/**
 * Compute the duration quality score (0 – DURATION_WEIGHT).
 *
 * Songs between 2 – 8 minutes receive the highest score.
 * Very short (<30 s) or very long (>15 min) tracks are penalized.
 */
function durationScore(durationSec: number | undefined): number {
  if (durationSec == null || durationSec <= 0) return DURATION_WEIGHT * 0.3;

  if (durationSec >= 120 && durationSec <= 480) {
    // 2 – 8 minutes: peak quality
    return DURATION_WEIGHT;
  }

  if (durationSec >= 60 && durationSec < 120) {
    // 1 – 2 minutes: still reasonable
    return DURATION_WEIGHT * 0.8;
  }

  if (durationSec > 480 && durationSec <= 900) {
    // 8 – 15 minutes: slightly long
    return DURATION_WEIGHT * 0.65;
  }

  if (durationSec < 30) {
    // Very short — likely not a proper song
    return DURATION_WEIGHT * 0.15;
  }

  if (durationSec > 900) {
    // > 15 minutes
    return DURATION_WEIGHT * 0.25;
  }

  return DURATION_WEIGHT * 0.5;
}

/**
 * Compute the channel quality score (0 – CHANNEL_WEIGHT).
 *
 * "topic" channels (auto-generated by YouTube Music) and channels whose
 * name contains the artist name are considered higher quality.
 */
function channelScore(track: Track): number {
  const artist = track.artist.toLowerCase();
  const title = track.title.toLowerCase();
  const combined = `${artist} ${title}`;

  // "topic" channels are official auto-generated releases
  if (combined.includes('topic')) return CHANNEL_WEIGHT;

  // Name looks like an official artist channel (e.g. "Artist - Topic")
  if (combined.includes('official')) return CHANNEL_WEIGHT * 0.9;

  // If artist name appears in the track title the metadata is likely accurate
  if (artist.length > 2 && title.includes(artist)) {
    return CHANNEL_WEIGHT * 0.7;
  }

  return CHANNEL_WEIGHT * 0.4;
}

/**
 * Compute the popularity / view-count proxy score (0 – POPULARITY_WEIGHT).
 *
 * Uses `playCount` as the primary signal, falling back to a flat middle value
 * when the data is unavailable.
 */
function popularityScore(track: Track): number {
  if (track.playCount == null || track.playCount <= 0) {
    return POPULARITY_WEIGHT * 0.4;
  }

  // Logarithmic scaling so huge outliers don't dominate.
  // log10(1) = 0, log10(1000) ≈ 3, log10(10_000_000) = 7
  const logPlays = Math.log10(Math.max(1, track.playCount));
  const normalised = Math.min(1, logPlays / 7); // cap at 10 M plays

  return POPULARITY_WEIGHT * (0.3 + 0.7 * normalised);
}

// ── RankingEngine ───────────────────────────────────────────────────────────

/**
 * Scores and ranks an array of search-result tracks for a given query.
 */
class RankingEngine {
  /**
   * Rank search results by relevance to the query string.
   *
   * @param results - Raw search results to rank.
   * @param query   - The user's search query.
   * @returns A new array sorted by descending relevance score.
   */
  rankResults(results: Track[], query: string): Track[] {
    const normalisedQuery = normalize(query);

    const scored = results.map((track) => {
      const normalisedTitle = normalize(track.title);

      const title = titleScore(normalisedTitle, normalisedQuery);
      const duration = durationScore(track.duration);
      const channel = channelScore(track);
      const popularity = popularityScore(track);

      const total = title + duration + channel + popularity;

      return { track, score: total };
    });

    scored.sort((a, b) => b.score - a.score);

    return scored.map((entry) => entry.track);
  }
}

/** Singleton ranking engine instance. */
export const rankingEngine = new RankingEngine();
